### ISSUE TITLE
Too many redirects 

### ISSUE THREAD

**Issue by smarajitdasgupta** [hugotox/nextjs-starter#1]
Hey I am giving your starter strategy a go and ran into the problem where logged out user is getting redirected on loop to 

http://localhost:3000/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/login?next=/

This is clearly happening from isServer becoming true in redirectToLogin() continuously

How may I solve this?

Edit:

In this case looks like _app.js getInitialProps is being called multiple times!!

**Comment by hugotox** [comment]
Thanks for reporting this! It was a bug in the Login component when wrapping it with the `withRouter` HOC, then I can't read the `isPublic` static prop, so removing the HOC fixed the issue.
Also updated a bunch of deps.
